---
# defaults file for roles/mediawiki/configuracion
# default mediawiki administrator
mediawiki_admin_user:     "admin"
mediawiki_admin_password: "admin"

mediawiki_name: "mediawiki"
mediawiki_title: "ENI"
mediawiki_directory: "/var/www/html/{{mediawiki_name}}"
mediawiki_maintenance_directory: "{{mediawiki_directory}}/mantenimiento"

# default database host: primera máquina del grupo apache -> comienza con índice [0].
mediawiki_db_host: "{{groups.apache.0}}"

# archivo de descarga mediawiki.
mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.36/mediawiki-1.36.1.tar.gz"

