---
# tasks file for roles/mediawiki/configuracion
- name: "mediawiki directorio"
  file:
    path: "{{mediawiki_directory}}"
    owner: "apache"
    group: "apache"
    state: directory

- name: "descompresión del archivo mediawiki"
  unarchive:
    src: "{{mediawiki_archive_url}}"
    dest: "{{mediawiki_directory}}"
    owner: "apache"
    group: "apache"
    remote_src: yes
    setype: httpd_sys_content_t
    # remover mediawiki-xx.x/ desde el path
    extra_opts: --transform=s/^mediawiki-[0-9\.]*\///

- name: "configuración de mediawiki"
  become: yes
  become_user: "apache"
  environment:
    LC_ALL: C
  args:
    creates: "{{mediawiki_directory}}/LocalSettings.php"
    chdir: "{{mediawiki_maintenance_directory}}"
  command:
    php install.php --scriptpath /{{mediawiki_name}}
       --dbname mediawiki --lang es
       --dbuser {{mediawiki_db_user}}
       --dbpass {{mediawiki_db_password}}
       --pass {{mediawiki_admin_password}}
       --dbserver {{mediawiki_db_host}}
       {{mediawiki_title}} {{mediawiki_admin_user}}

- name: "fix mediawiki redirection"
  lineinfile:
    path: "{{mediawiki_directory}}/LocalSettings.php"
    regex: '\$wgServer.*'
    line: '$wgServer = $_SERVER["HOST"];'
